### ISSUE TITLE
RTE pre-sale validation: Builtin Uart Pinout - how to proceed?

### ISSUE THREAD

**Issue by Stanislaw-bnk** [3mdeb/hardware-presale-validation#1]
I have some questions about two validation steps from the RTE pre-sale validation procedure
**Step 4:** [**Builtin Uart Pinout**](https://gitlab.com/3mdeb/rte/docs/-/blob/master/docs/rte_presale_validation.md#4-builtin-uart-pinout). 

The steps are as follows:
- Put the two jumpers on RTE J16 Header so that they join COM and EXT rows both on RX and TX columns. - **DONE**
- Turn on the relay as described in the previous step. - **DONE**
- Find the IP of the RTE using the ip a command - **DONE** (IP: 192.168.4.180)
- Connect through SSH to the platform by `ssh root@<ip>`

After entering `ssh root@192.168.4.180`, I get:
```
root@rte:~# ssh root@192.168.4.180                                              
root@192.168.4.180's password:                                                  
Last login: Wed May  8 11:24:13 2024                                            
root@rte:~# [   32.479609] vcc3v0: disabling                                    
[   32.482612] vcc5v0: disabling   
```
Is this the correct reading?

Next:
- Make sure the device connected with jumpers to serial is powered on and its serial is working (It may be useful to check if it received input and provides output using a USB-UART converter connected to your PC). - **DONE**
- Check the serial connection using `minicom -D /dev/ttyS1`. Output from the platform should be actively appearing inside the minicom window. If there is no output, try restarting the relay by setting `gpio199` to `0`, then to `1`.

When I enter this command, all I get is:
```
minicom -D /dev/ttyS1                                                           


Welcome to minicom 2.7.1

OPTIONS: I18n 
Compiled on Mar 12 2024, 13:39:32.
Port /dev/ttyS1, 11:24:03

Press CTRL-A Z for help on special keys
```

And also:
**Step 6:** [**Builtin RS232 Port**](https://gitlab.com/3mdeb/rte/docs/-/blob/master/docs/rte_presale_validation.md#6-builtin-rs232-port)

After the `ssh root@<ip>`, all I get is:
```
root@rte:~# ssh root@192.168.4.180                                              
root@192.168.4.180's password:                                                  
Last login: Tue May 14 06:19:46 2024 from 192.168.4.180   
```
The relay is at `echo 1 > /sys/class/gpio/gpio199/value`

**Comment by Stanislaw-bnk** [comment]
Punkty 4 i 6 myślę, że udało się wyjaśnić. Instrukcja raczej nie wymaga tutaj poprawek, jedynie wymagała mojego zrozumienia, jakiego outputu powinienem się spodziewać.
Jednak nadal walczę z ostatnim punktem [7. SPI Header](https://gitlab.com/3mdeb/rte/docs/-/blob/master/docs/rte_presale_validation.md#7-spi-header), który nie jest dla mnie zrozumiały, jednak na to wystawię osobne issue.

**Comment by BeataZdunczyk** [comment]
> Punkty 4 i 6 myślę, że udało się wyjaśnić. Instrukcja raczej nie wymaga tutaj poprawek, jedynie wymagała mojego zrozumienia, jakiego outputu powinienem się spodziewać.

@Stanislaw-bnk dodajmy ten output do instrukcji zatem
